name: mojidraw
description: Draw your favourite Emoji art

publish_to: 'none'

version: 1.0.0-alpha.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  emojis: ^0.9.3
  extended_tabs: ^2.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.3
  intl: ^0.17.0
  provider: ^5.0.0
  snapping_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  lint: ^1.5.3
  test: ^1.15.7

flutter:
  uses-material-design: true

  fonts:
    - family: JoyPixels
      fonts:
        - asset: fonts/joypixels-android.ttf