name: mojidraw
description: Draw your favourite Emoji art

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.8.0
  test: ^1.15.7

flutter:
  uses-material-design: true

  fonts:
    - family: JoyPixels
      fonts:
        - asset: fonts/joypixels-android.ttf