name: mojidraw
description: Draw your favourite Emoji art

publish_to: 'none'

version: 1.0.0-alpha.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  emojis: ^0.9.3
  extended_tabs: ^2.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.6
  intl: ^0.17.0
  package_info: ^2.0.0
  pedantic: ^1.11.0
  permission_handler: ^7.1.0
  provider: ^5.0.0
  snapping_sheet: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  lint: ^1.5.3
  test: ^1.16.5

flutter:
  uses-material-design: true

  assets:
    - images/mojidraw_banner.png
    - images/mojidraw_logo.png
    - test/dummy.png

  fonts:
    - family: JoyPixels
      fonts:
        - asset: fonts/joypixels-android.ttf