name: mojidraw
description: Draw your favourite Emoji art
homepage: https://mojidraw.app

publish_to: 'none'

version: 1.0.0-alpha.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  emojis: ^0.9.3
  extended_tabs: ^2.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  package_info: ^2.0.0
  permission_handler: ^7.1.0
  provider: ^5.0.0
  snapping_sheet: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  pedantic: ^1.11.0
  test: ^1.16.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/mojidraw_banner.png
    - assets/images/mojidraw_logo.png

  fonts:
    - family: JoyPixels
      fonts:
        - asset: assets/fonts/joypixels-android.ttf