name: mojidraw
description: Mojidraw - the app that lets you become an emoji artist!
homepage: https://mojidraw.app

publish_to: 'none'

version: 1.0.0-beta.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  emojis: ^0.9.3
  extended_tabs: ^2.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  package_info: ^2.0.2
  permission_handler: ^8.1.2
  provider: ^5.0.0
  snapping_sheet: ^3.1.0
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  pedantic: ^1.11.1
  test: ^1.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/mojidraw_banner.png
    - assets/images/mojidraw_logo.png

  fonts:
    - family: JoyPixels
      fonts:
        - asset: assets/fonts/joypixels-android.ttf